name: Build and test RPMs
on: [push]

jobs:
  build-rpms-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Prepare Docker
        run: |
          echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker > /dev/null &&
            sudo service docker restart

      - run: mkdir _build_results

      - name: Build RPMs
        run: |
          docker run -v $(pwd):/${GITHUB_REPOSITORY##*/} \
                     -v $(pwd)/_build_results:/u/_build_results \
                     -e REPO_NAME=${GITHUB_REPOSITORY##*/} \
                     -e GET_FILES=True \
                     --privileged \
                     opensciencegrid/osg-build \
                     build-from-github

      - run: ls -lR
