name: Build and test RPMs
on: [push]

jobs:
  build-rpms-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: mkdir _build_dir

      - name: Build RPMs
        run: |
          docker run -v "$PWD:/${GITHUB_REPOSITORY##*/}" \
                     -v "$PWD/_build_dir:/u/_build_dir" \
                     --privileged \
                     opensciencegrid/osg-build \
                     osg-build --verbose mock --mock-config-from-koji=osg-upcoming-el7-build _build_dir

      # TODO add tests here! RPMs should be available in `_build_dir`
